### ISSUE TITLE
tarsnap alternative

### ISSUE THREAD

**Issue by andrewchambers** [rocketnewton/dotfiles#1]
I am the author of https://github.com/andrewchambers/bupstash which gives similar functionality to tarnsap but is open source and in my benchmarks far better performance.

I also have an online repository service in closed beta at https://bupstash.io/.

Feel free to close this ticket.

**Comment by jrnewton** [comment]
Sorry about the spam tag - Andrew pointed out that I had asked for recommendations of tarsnap alternatives in 2e518981bafbd48d14f6f25461c6d6e63f4c6c43. 

Mea Culpa
